"""
uenotomoki-docker-django-nlb-07bde5140e8878e1.elb.ap-northeast-1.amazonaws.com

Django settings for app project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_q$$1dni!@8kkrljijr9%f%_4+&%#r=hdi-#obhf+avgo!8wc1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',  # 追加
    'social_django',  # 追加
    'django.contrib.sites',#user_account
    'allauth',             #user_account
    'allauth.account',     #user_account
    'allauth.socialaccount', #user_account
    'bootstrap4', #bootstrap4
    'widget_tweaks', #widget_tweaks
    'storages', # AWS S3
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  # 追加
]

ROOT_URLCONF = 'app.urls'

import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # 追加
                'social_django.context_processors.login_redirect', # 追加
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

##############################################################
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
##############################################################
###
DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.postgresql_psycopg2',
         'NAME': 'uenotomoki_skype_stripe_db_ins',
         'USER': 'postgres',
         'PASSWORD': 'postgres',
         'HOST': 'database-1.c5913tth0i0f.ap-northeast-1.rds.amazonaws.com',
         'PORT': '5432',
     }
 }
##############################################################


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'PASSWORD': 'postgres',
#         'HOST': 'db',
#         'PORT': 5432,
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

#STATIC_URL = 'static/'

#20221220
#STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

####################################################google認証####################################################
# AUTHENTICATION_BACKENDS = (
#     'social_core.backends.open_id.OpenIdAuth',  # OpenId用
#     'social_core.backends.google.GoogleOpenId',  # Google OpenId用
#     'social_core.backends.google.GoogleOAuth2',  # Google OAuth2用
#     'social_core.backends.github.GithubOAuth2',  # Github用
#     'social_core.backends.twitter.TwitterOAuth',  # Twitter用
#     'social_core.backends.facebook.FacebookOAuth2',  # Facebook用
#     'django.contrib.auth.backends.ModelBackend',  # デフォルトバックエンド、必須。
# )
AUTHENTICATION_BACKENDS = (
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',
    'social_core.backends.twitter.TwitterOAuth',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '931297300149-d0k99q3f3t09sbvr53qj7bf21qq311fg.apps.googleusercontent.com'  # クライアントID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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' # クライアント シークレット

#「LOGIN_URL」は、ログインが必要なページで認証していないユーザーがアクセスした場合に、リダイレクト先のURLを指定するもの
# LOGIN_URL = 'login'
# #LOGIN_URL = 'myapp:login'

SITE_ID = 1     #追加20221216_user_account

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'logout'

#ログインした後にリダイレクトするURLを指定するもの
LOGIN_REDIRECT_URL = '/'

#SOCIAL_AUTH_POSTGRES_JSONFIELD = True

# SOCIAL_AUTH_PIPELINE = (
#     'social.pipeline.social_auth.social_details',
#     'social.pipeline.social_auth.social_uid',
#     'social.pipeline.social_auth.auth_allowed',
#     'social.pipeline.social_auth.social_user',
#     'social.pipeline.user.get_username',
#     'social.pipeline.user.create_user',
#     'project_name.custom_pipeline.set_superuser',  # 用意した関数へのパス
#     'social.pipeline.social_auth.associate_user',
#     'social.pipeline.social_auth.load_extra_data',
#     'social.pipeline.user.user_details'
# )

# TEMPLATE_CONTEXT_PROCESSORS = (
#    'django.contrib.auth.context_processors.auth',
#    'django.core.context_processors.debug',
#    'django.core.context_processors.i18n',
#    'django.core.context_processors.media',
#    'django.core.context_processors.static',
#    'django.core.context_processors.tz',
#    'django.contrib.messages.context_processors.messages',
#    'social.apps.django_app.context_processors.backends',
#    'social.apps.django_app.context_processors.login_redirect',
# )

#SOCIAL_AUTH_URL_NAMESPACE = 'social'

####################################################stripe####################################################

# Stripeのパブリックキー
STRIPE_PUBLIC_KEY = 'pk_test_51MCcIOJBZi7uqbLmOa6NLcL3ofC703h97LvVpzQF6N2eijDm0APq8RwW6o0tSeUooqigBW15BRdyH8h8XqroWC0400ZDqGSqW3'
# Stripeのシークレットキー
STRIPE_SECRET_KEY = 'sk_test_51MCcIOJBZi7uqbLmaYPfskbYxnDD9ElCx1A6aXf9QkgrYvMQzn7sjZ9V4KCYTOz57hk284bCBTXto3ni3PYkd6io007Q9nZSuP'
# StripeのWebhookのシークレットキー
STRIPE_WEBHOOK_SECRET = 'whsec_3263e11fee8dd283e591c38d4d0a19705bfd4330bf84cd792241c8682292120f'
########################################################################################################

####################################################stripe####################################################
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' #設定しなくてもデフォルトでこの値になるっぽい
EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST = 'smtp.googlemail.com' #これでもいける
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'githubfreezing45@gmail.com'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER # send_mailのfromがNoneの場合自動で入る。
#EMAIL_HOST_PASSWORD = 'git00045'
EMAIL_HOST_PASSWORD = 'axhdfmrhvmhxetvd'
########################################################################################################

####################################################AWS####################################################
#SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
#SESSION_COOKIE_SAMESITE = "None"
# SESSION_COOKIE_HTTPONLY = False
# SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['state']
# SESSION_COOKIE_SECURE = False
########################################################################################################

#####################################################user_account###################################################
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_USERNAME_REQUIRED = False 
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
# ACCOUNT_EMAIL_REQUIRED = True
########################################################################################################

#STATIC_URL = '/static/'
############################################
#       AWS S3 setting
############################################


# アカウントの設定
AWS_ACCESS_KEY_ID = 'AKIAZS7TR35JJRJ3VFOU'#'アクセスキー'
AWS_SECRET_ACCESS_KEY = 'PGbCkeEQRytnp/BQ51KoKHTvyEPg4M48q4ijCefK'#'シークレットアクセスキー'
AWS_STORAGE_BUCKET_NAME = 'uenotomoki-skype-stripe-s3bucket'#'バケット名'

# 静的ファイルの設定
AWS_LOCATION = 'static'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
AWS_QUERYSTRING_AUTH = False

# S3へファイルをアップロードするための設定
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

############################################
# 保存先URL
STATIC_URL = 'https://%s.s3.ap-northeast-1.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
AWS_LOCATION = 'static'

############################################
MEDIA_URL = 'https://%s.s3.ap-northeast-1.amazonaws.com/'
############################################



######################################################################################################